{
 "title": "K8s-livelogs-search",
 "description": "Container/Pod Log Dashboard(Loki as DataSource)",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource_loki", "query": "loki" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values({namespace=~\".+\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {}
   },
   {
    "name": "Container",
    "query": {}
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": "label_values({namespace=\"$namespace\"}, stream)"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  { "title": "EC2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"$namespace\", stream=~\"$stream\", pod=~\"$pod\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $searchable_pattern",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"$namespace\", stream=~\"$stream\", pod=~\"$pod\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", pod=~\"$pod\", stream=~\"$stream\"} |~ \"(?i)$searchable_pattern\""
    }
   ]
  }
 ]
}